// import 'package:flutter/material.dart';

class Author {
  String death =
      'After suffering a number of strokes, Stoker died at No. 26 St George\'s Square, London on 20 April 1912. Some biographers attribute the cause of death to tertiary syphilis, others to overwork.[28] He was cremated, and his ashes were placed in a display urn at Golders Green Crematorium in north London. The ashes of Irving Noel Stoker, the author\'s son, were added to his father\'s urn following his death in 1961. The original plan had been to keep his parents\' ashes together, but after Florence Stoker\'s death, her ashes were scattered at the Gardens of Rest.';
  String writings =
      'Stoker visited the English coastal town of Whitby in 1890, and that visit was said to be part of the inspiration for Dracula. He began writing novels while working as manager for Henry Irving and secretary and director of London\'s Lyceum Theatre, beginning with The Snake\'s Pass in 1890 and Dracula in 1897. During this period, Stoker was part of the literary staff of The Daily Telegraph in London, and he wrote other fiction, including the horror novels The Lady of the Shroud (1909) and The Lair of the White Worm (1911). He published his Personal Reminiscences of Henry Irving in 1906, after Irving\'s death, which proved successful, and managed productions at the Prince of Wales Theatre. Before writing Dracula, Stoker met Ármin Vámbéry, a Hungarian-Jewish writer and traveller (born in Szent-György, Kingdom of Hungary now Svätý Jur, Slovakia). Dracula likely emerged from Vámbéry\'s dark stories of the Carpathian mountains. Stoker then spent several years researching Central and East European folklore and mythological stories of vampires. The 1972 book In Search of Dracula by Radu Florescu and Raymond McNally claimed that the Count in Stoker\'s novel was based on Vlad III Dracula. At most however, Stoker borrowed only the name and \"scraps of miscellaneous information\" about Romanian history, according to one expert, Elizabeth Miller; further, there are no comments about Vlad III in the author\'s working notes. Dracula is an epistolary novel, written as a collection of realistic but completely fictional diary entries, telegrams, letters, ship\'s logs, and newspaper clippings, all of which added a level of detailed realism to the story, a skill which Stoker had developed as a newspaper writer. At the time of its publication, Dracula was considered a "\straightforward horror novel\" based on imaginary creations of supernatural life. \"It gave form to a universal fantasy ... and became a part of popular culture.\" According to the Encyclopedia of World Biography, Stoker\'s stories are today included in the categories of\ "horror fiction\", \"romanticized Gothic\" stories, and \"melodrama\" They are classified alongside other \"works of popular fiction\" such as Mary Shelley\'s Frankenstein, which also used the \"myth-making\" and story-telling method of having multiple narrators telling the same tale from different perspectives. According to historian Jules Zanger, this leads the reader to the assumption that \"they can\'t all be lying\".';
  String earlylife =
      'Stoker was born on 8 November 1847 at 15 Marino Crescent, Clontarf, on the northside of Dublin, Ireland. His parents were Abraham Stoker (1799–1876) from Dublin and Charlotte Mathilda Blake Thornley (1818–1901), who was raised in County Sligo. Stoker was the third of seven children, the eldest of whom was Sir Thornley Stoker, 1st Bt.. Abraham and Charlotte were members of the Church of Ireland Parish of Clontarf and attended the parish church with their children, who were baptised there, and Abraham was a senior civil servant. Stoker was bedridden with an unknown illness until he started school at the age of seven, when he made a complete recovery. Of this time, Stoker wrote, "I was naturally thoughtful, and the leisure of long illness gave opportunity for many thoughts which were fruitful according to their kind in later years." He was educated in a private school run by the Rev. William Woods. After his recovery, he grew up without further serious illnesses, even excelling as an athlete (he was named University Athlete, participating in multiple sports) at Trinity College, Dublin, which he attended from 1864 to 1870. He graduated with a BA in 1870, and pursued his MA in 1875. Though he later in life recalled graduating "with honours in mathematics," this appears to have been a mistake. He was auditor of the College Historical Society (the Hist) and president of the University Philosophical Society, where his first paper was on Sensationalism in Fiction and Society.';
}
